name: petopia
version: "1.0.0"
config-version: 2

profile: petopia

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  petopia:
    staging:
      +materialized: view
    marts:
      +materialized: table
