-- ============================================================
-- Pet Store Supply Chain – PostgreSQL Schema
-- Database: pet_store_scm
-- PostgreSQL owns: forecasts, alerts, analytics aggregates
-- ============================================================

-- Run as: psql -U postgres -d pet_store_scm -f postgres_schema.sql

CREATE TABLE IF NOT EXISTS sku_forecasts (
    id              BIGSERIAL       PRIMARY KEY,
    forecast_date   DATE            NOT NULL,
    sku_id          VARCHAR(20)     NOT NULL,
    horizon_days    SMALLINT        NOT NULL DEFAULT 30,
    p10_total       NUMERIC(12,2),
    p50_total       NUMERIC(12,2),
    p90_total       NUMERIC(12,2),
    p50_daily       NUMERIC(10,2),
    forecast_source VARCHAR(50)     NOT NULL DEFAULT 'statistical',  -- 'tft' or 'statistical'
    model_version   VARCHAR(50),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (forecast_date, sku_id, horizon_days, forecast_source)
);

CREATE INDEX IF NOT EXISTS idx_forecasts_sku        ON sku_forecasts (sku_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_date       ON sku_forecasts (forecast_date);
CREATE INDEX IF NOT EXISTS idx_forecasts_created_at ON sku_forecasts (created_at DESC);

-- ------------------------------------------------------------
-- Inventory alerts log (generated by the agent/MCP server)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_alerts (
    id              BIGSERIAL       PRIMARY KEY,
    alert_date      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    sku_id          VARCHAR(20)     NOT NULL,
    alert_type      VARCHAR(30)     NOT NULL, -- 'CRITICAL', 'WARNING', 'STOCKOUT'
    days_of_supply  NUMERIC(8,2),
    current_inventory INT,
    avg_daily_demand  NUMERIC(10,2),
    lead_time_days  SMALLINT,
    recommended_action TEXT,
    resolved        BOOLEAN         NOT NULL DEFAULT FALSE,
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_alerts_sku       ON inventory_alerts (sku_id);
CREATE INDEX IF NOT EXISTS idx_alerts_date      ON inventory_alerts (alert_date DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_type      ON inventory_alerts (alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved  ON inventory_alerts (resolved);

-- ------------------------------------------------------------
-- Demand anomaly log
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS demand_anomalies (
    id              BIGSERIAL       PRIMARY KEY,
    detected_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    sku_id          VARCHAR(20)     NOT NULL,
    anomaly_date    DATE            NOT NULL,
    observed_demand INT             NOT NULL,
    expected_demand NUMERIC(10,2),
    z_score         NUMERIC(6,3),
    anomaly_type    VARCHAR(30),    -- 'SPIKE', 'DROP', 'TREND_BREAK'
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_anomalies_sku    ON demand_anomalies (sku_id);
CREATE INDEX IF NOT EXISTS idx_anomalies_date   ON demand_anomalies (anomaly_date DESC);

-- ------------------------------------------------------------
-- Monthly aggregated KPIs (pre-computed by analytics job)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS monthly_kpis (
    id                  BIGSERIAL       PRIMARY KEY,
    year_month          CHAR(7)         NOT NULL,   -- 'YYYY-MM'
    sku_id              VARCHAR(20)     NOT NULL,
    total_demand        BIGINT,
    avg_daily_demand    NUMERIC(10,2),
    avg_inventory       NUMERIC(12,2),
    min_inventory       INT,
    stockout_days       SMALLINT        DEFAULT 0,
    revenue_est_usd     NUMERIC(14,2),
    fill_rate_pct       NUMERIC(5,2),
    UNIQUE (year_month, sku_id)
);

CREATE INDEX IF NOT EXISTS idx_kpis_sku         ON monthly_kpis (sku_id);
CREATE INDEX IF NOT EXISTS idx_kpis_year_month  ON monthly_kpis (year_month);

-- ------------------------------------------------------------
-- Supplier risk scores (PostgreSQL analytics)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_risk_scores (
    id                  BIGSERIAL       PRIMARY KEY,
    score_date          DATE            NOT NULL DEFAULT CURRENT_DATE,
    supplier_name       VARCHAR(150)    NOT NULL,
    risk_score          NUMERIC(5,2),   -- 0-100, higher = riskier
    on_time_score       NUMERIC(5,2),
    quality_score       NUMERIC(5,2),
    lead_time_variance  NUMERIC(5,2),
    concentration_risk  NUMERIC(5,2),   -- % of SKUs sourced from this supplier
    notes               TEXT,
    UNIQUE (score_date, supplier_name)
);

CREATE INDEX IF NOT EXISTS idx_risk_supplier    ON supplier_risk_scores (supplier_name);
CREATE INDEX IF NOT EXISTS idx_risk_date        ON supplier_risk_scores (score_date DESC);

-- ------------------------------------------------------------
-- Agent query log (audit trail)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_query_log (
    id              BIGSERIAL       PRIMARY KEY,
    session_id      UUID            NOT NULL DEFAULT gen_random_uuid(),
    queried_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    provider        VARCHAR(50),    -- 'anthropic', 'openai', 'groq', 'gemini'
    model           VARCHAR(100),
    user_query      TEXT,
    tools_called    TEXT[],         -- array of tool names called
    response_tokens INT,
    duration_ms     INT
);

CREATE INDEX IF NOT EXISTS idx_query_log_date   ON agent_query_log (queried_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_log_session ON agent_query_log (session_id);

-- ============================================================
-- Helper views
-- ============================================================

-- Current inventory status view (for quick MCP tool queries)
-- NOTE: This view references the daily_demand table in MySQL.
-- In a real setup use a foreign data wrapper (postgres_fdw).
-- For this project, the MCP server queries each DB separately.

-- Forecast accuracy view
CREATE OR REPLACE VIEW forecast_accuracy AS
SELECT
    f.sku_id,
    f.forecast_date,
    f.horizon_days,
    f.p50_daily        AS predicted_daily,
    f.forecast_source,
    f.created_at
FROM sku_forecasts f
ORDER BY f.created_at DESC;

-- Active alerts view
CREATE OR REPLACE VIEW active_alerts AS
SELECT *
FROM inventory_alerts
WHERE resolved = FALSE
ORDER BY alert_date DESC;
